# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `iconv` gem.
# Please instead update this file by running `bin/tapioca gem iconv`.


# source://iconv//lib/iconv/version.rb#1
class Iconv
  def initialize(*_arg0); end

  def close; end
  def conv(*_arg0); end
  def discard_ilseq=; end
  def discard_ilseq?; end
  def iconv(*_arg0); end
  def transliterate=; end
  def transliterate?; end
  def trivial?; end

  class << self
    def charset_map; end
    def conv(_arg0, _arg1, _arg2); end
    def ctlmethods; end
    def iconv(*_arg0); end
    def list; end
    def open(*_arg0); end
  end
end

class Iconv::BrokenLibrary < ::RuntimeError
  include ::Iconv::Failure
end

module Iconv::Failure
  def initialize(_arg0, _arg1, _arg2); end

  def failed; end
  def inspect; end
  def success; end
end

class Iconv::IllegalSequence < ::ArgumentError
  include ::Iconv::Failure
end

class Iconv::InvalidCharacter < ::ArgumentError
  include ::Iconv::Failure
end

class Iconv::InvalidEncoding < ::ArgumentError
  include ::Iconv::Failure
end

class Iconv::OutOfRange < ::RuntimeError
  include ::Iconv::Failure
end

# source://iconv//lib/iconv/version.rb#2
Iconv::VERSION = T.let(T.unsafe(nil), String)
