# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `karafka-testing` gem.
# Please instead update this file by running `bin/tapioca gem karafka-testing`.


# Main Karafka module
#
# source://karafka-testing//lib/karafka/testing.rb#4
module Karafka
  class << self
    # source://karafka/2.4.2/lib/karafka.rb#94
    def boot_file; end

    # source://karafka/2.4.2/lib/karafka.rb#63
    def core_root; end

    # source://karafka/2.4.2/lib/karafka.rb#25
    def env; end

    # source://karafka/2.4.2/lib/karafka.rb#33
    def env=(environment); end

    # source://karafka/2.4.2/lib/karafka.rb#53
    def gem_root; end

    # source://karafka/2.4.2/lib/karafka.rb#38
    def logger; end

    # source://karafka/2.4.2/lib/karafka.rb#48
    def monitor; end

    # source://karafka/2.4.2/lib/karafka.rb#68
    def pro?; end

    # source://karafka/2.4.2/lib/karafka.rb#43
    def producer; end

    # source://karafka/2.4.2/lib/karafka.rb#74
    def rails?; end

    # source://karafka/2.4.2/lib/karafka.rb#103
    def refresh!; end

    # source://karafka/2.4.2/lib/karafka.rb#58
    def root; end
  end
end

# Testing lib module
#
# source://karafka-testing//lib/karafka/testing.rb#6
module Karafka::Testing
  class << self
    # If you do not initialize Karafka always within your specs, do not include/use this lib
    # in places where Karafka would not be loaded.
    #
    # @raise [Karafka::Testing::Errors::KarafkaNotInitializedError]
    #
    # source://karafka-testing//lib/karafka/testing.rb#23
    def ensure_karafka_initialized!; end

    # Makes sure, that we do not use the testing stubs, etc when Karafka app is not loaded
    #
    # You should never use karafka-testing primitives when framework is not loaded because
    # testing lib stubs certain pieces of Karafka that need to be initialized.
    #
    # @raise [Karafka::Testing::Errors::KarafkaNotLoadedError]
    #
    # source://karafka-testing//lib/karafka/testing.rb#12
    def ensure_karafka_loaded!; end
  end
end
