# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ollama::CreateChunkJob`.
# Please instead update this file by running `bin/tapioca dsl Ollama::CreateChunkJob`.


class Ollama::CreateChunkJob
  class << self
    sig do
      params(
        data: T.untyped,
        message_ids: T.untyped,
        block: T.nilable(T.proc.params(job: Ollama::CreateChunkJob).void)
      ).returns(T.any(Ollama::CreateChunkJob, FalseClass))
    end
    def perform_later(data:, message_ids:, &block); end

    sig { params(data: T.untyped, message_ids: T.untyped).returns(T.untyped) }
    def perform_now(data:, message_ids:); end
  end
end
