# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ollama::SyncEmbeddingsJob`.
# Please instead update this file by running `bin/tapioca dsl Ollama::SyncEmbeddingsJob`.


class Ollama::SyncEmbeddingsJob
  class << self
    sig do
      params(
        chunk_id: T.untyped,
        block: T.nilable(T.proc.params(job: Ollama::SyncEmbeddingsJob).void)
      ).returns(T.any(Ollama::SyncEmbeddingsJob, FalseClass))
    end
    def perform_later(chunk_id, &block); end

    sig { params(chunk_id: T.untyped).returns(T.untyped) }
    def perform_now(chunk_id); end
  end
end
