# frozen_string_literal: true

module Ollama
  class Events
    VERSION = '0.1.0'
    CHAT_STARTED = 'CHAT_STARTED.OLLAMA'
    CHAT_STOPPED = 'CHAT_STOPPED.OLLAMA'
    MESSAGE_CREATED = 'MESSAGE_CREATED.OLLAMA'
    MESSAGE_UPDATED = 'MESSAGE_UPDATED.OLLAMA'
    MESSAGE_DESTROYED = 'MESSAGE_DESTROYED.OLLAMA'
    SYNC_EMBEDDING = 'SYNC_EMBEDDING.OLLAMA'
  end
end
