# frozen_string_literal: true

module Ollama
  class Events
    VERSION = '0.1.0'
    START_CHAT = 'START_CHAT.OLLAMA'
    STOP_CHAT = 'STOP_CHAT.OLLAMA'
    MESSAGE_CREATED = 'MESSAGE_CREATED.OLLAMA'
    MESSAGE_UPDATED = 'MESSAGE_UPDATED.OLLAMA'
    MESSAGE_DESTROYED = 'MESSAGE_DESTROYED.OLLAMA'
  end
end
