# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Karafka::Testing::Helpers; end
module KarafkaLoggerListener::Errors::UnsupportedCaseError; end
module RSpec::Matchers; end
module RSpec::Matchers::DSL; end
